---
- name: "Enable EPEL repo"
  package:
    name: "epel-release"
    state: present
  become: True
  when: enable_epel is defined and enable_epel
- name: "Install required packages"
  package:
    name: "{{ pkglist }}"
    state: present
  become: True
...