---
- name: "Include os specific variables"
  include_vars: "packages-{{ ansible_os_family }}-{{ ansible_distribution_version }}.yml"
- name: "Call install-packages task for RedHat like systems"
  include_tasks: install-packages-RedHat.yml
  when: ansible_os_family == "RedHat"
- name: "Call install-packages task for Debian like systems"
  include_tasks: install-packages-Debian.yml
  when: ansible_os_family == "Debian"
...