namespace: infra_monkey
name: ansible_general
version: 0.0.4

readme: README.md
authors:
  - Antoine Gatineau <antoine.gatineau@infra-monkey.com>
description: A ansible collection for general purpose linux system management
license:
  - Apache-2.0
tags:
  - "ansible"
  - "collection"

dependencies: {}
repository: https://github.com/infra-monkey/ansible_general
documentation: https://github.com/infra-monkey/ansible_general/blob/main/README.md
homepage: https://github.com/infra-monkey/ansible_general
issues: https://github.com/infra-monkey/ansible_general/issues
