---
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Run ansible-lint
        uses: ansible/ansible-lint-action@main
        with:
          override-deps: |
            rich>=9.5.1,<11.0.0
          targets: |
            roles/*/*/*.yml
          args: "--exclude roles/*/.github/ --exclude roles/*/molecule/"
      - name: Run Python linters
        uses: rjeffman/python-lint-action@v2
