---
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      # - uses: actions/setup-python@v2
      #   with:
      #     python-version: "3.9"

      - name: Run ansible-lint
        uses: ansible/ansible-lint-action@master
        with:
          targets: |
            playbooks/*.yml
            playbooks/*/*.yml
      - name: Run yaml-lint
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: roles/
          config_data: |
            extends: default
            rules:
              line-length: disable
      - name: Run Python linters
        uses: rjeffman/python-lint-action@v2
