---
name: Molecule Test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  molecule-check:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8]
        distro:
          - centos8
          # - centos7
          # - debian10
    steps:
      - uses: actions/checkout@v2
        with:
          path: molecule_check
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install molecule[ansible] flake8
      - name: Test with molecule
        working-directory: molecule_check
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
        run: molecule test
        with:
          image: "${{ matrix.distro }}"
